# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import images_src.chat_images_src,images_src.login_images_src
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import Qt


class Ui_registerWindow(object):
    def __init__(self,registerWindow):
        super(Ui_registerWindow, self).__init__()
        self.setupUi(registerWindow)

    def setupUi(self, registerWindow):
        registerWindow.setObjectName("registerWindow")
        registerWindow.resize(300, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(registerWindow.sizePolicy().hasHeightForWidth())
        registerWindow.setSizePolicy(sizePolicy)
        registerWindow.setMinimumSize(QtCore.QSize(300, 300))
        registerWindow.setMaximumSize(QtCore.QSize(300, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/login_window/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        registerWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(registerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(110, 10, 71, 71))
        self.graphicsView.setStyleSheet("border-image: url(:/login_window/images/icon.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(40, 110, 16, 16))
        self.graphicsView_2.setStyleSheet("border-image: url(:/login_window/images/user_login.jpg);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_3.setGeometry(QtCore.QRect(40, 140, 16, 16))
        self.graphicsView_3.setStyleSheet("border-image: url(:/login_window/images/password_login.jpg);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_4.setGeometry(QtCore.QRect(40, 170, 16, 16))
        self.graphicsView_4.setStyleSheet("border-image: url(:/login_window/images/password_login.jpg);")
        self.graphicsView_4.setObjectName("graphicsView_4")
        
        self.username_register = QtWidgets.QLineEdit(self.centralwidget)
        self.username_register.setGeometry(QtCore.QRect(70, 110, 180, 20))
        self.username_register.setMaxLength(20)
        self.username_register.setObjectName("username_register")
        
        self.password_register = QtWidgets.QLineEdit(self.centralwidget)
        self.password_register.setGeometry(QtCore.QRect(70, 140, 180, 20))
        self.password_register.setMaxLength(20)
        self.password_register.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_register.setObjectName("password_register")
        
        self.password_register_check = QtWidgets.QLineEdit(self.centralwidget)
        self.password_register_check.setGeometry(QtCore.QRect(70, 170, 180, 20))
        self.password_register_check.setMaxLength(20)
        self.password_register_check.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_register_check.setObjectName("password_register_check")
        
        self.ok_register_button = QtWidgets.QPushButton(self.centralwidget)
        self.ok_register_button.setGeometry(QtCore.QRect(40, 210, 211, 21))
        self.ok_register_button.setStyleSheet("border-image: url(:/chat/images/click.png);")
        self.ok_register_button.setObjectName("ok_register_button")
        self.ok_register_button.setCursor(Qt.PointingHandCursor)

        registerWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(registerWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 22))
        self.menubar.setObjectName("menubar")
        registerWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(registerWindow)
        self.statusbar.setObjectName("statusbar")
        registerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(registerWindow)
        QtCore.QMetaObject.connectSlotsByName(registerWindow)

    def retranslateUi(self, registerWindow):
        _translate = QtCore.QCoreApplication.translate
        registerWindow.setWindowTitle(_translate("registerWindow", "注册账号"))
        self.username_register.setPlaceholderText(_translate("registerWindow", "用户名"))
        self.password_register.setPlaceholderText(_translate("registerWindow", "密码"))
        self.password_register_check.setPlaceholderText(_translate("registerWindow", "再次输入密码"))
        self.ok_register_button.setText(_translate("registerWindow", "注 册 账 号"))
    
    